apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    app: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: 
      limits: 
        memory: "256Mi"
        cpu: "0.5"
    requests:
        memory: "128Mi"
        cpu: "0.3"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
